# Generated by Django 5.1.15 on 2026-02-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ne', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('election_date', models.DateField()),
                ('total_seats_fptp', models.PositiveSmallIntegerField()),
                ('total_seats_pr', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ne', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ne', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='elections.province')),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='elections.district')),
            ],
            options={
                'verbose_name_plural': 'constituencies',
                'constraints': [models.UniqueConstraint(fields=('district', 'number'), name='uq_constituency_district_number')],
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name_ne'], name='elections_d_name_ne_7bf6ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('province', 'name_ne'), name='uq_district_province_name'),
        ),
    ]
