# Generated by Django 5.1.15 on 2026-02-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField()),
                ('election_type', models.CharField(choices=[('fptp', 'First Past The Post'), ('pr', 'Proportional Representation')], max_length=4)),
                ('name_ne', models.CharField(max_length=300)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('father_name', models.CharField(blank=True, max_length=300)),
                ('spouse_name', models.CharField(blank=True, max_length=300)),
                ('address', models.TextField(blank=True)),
                ('citizenship_district', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=300)),
                ('experience', models.TextField(blank=True)),
                ('other_details', models.TextField(blank=True)),
                ('election_symbol_code', models.PositiveIntegerField(blank=True, null=True)),
                ('election_symbol_name', models.CharField(blank=True, max_length=100)),
                ('votes_received', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('closed_list_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('voter_id', models.CharField(blank=True, max_length=50)),
                ('inclusion_group', models.CharField(blank=True, max_length=100)),
                ('has_disability', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='parties.party')),
            ],
            options={
                'indexes': [models.Index(fields=['election', 'election_type'], name='candidates__electio_b06406_idx'), models.Index(fields=['election', 'party'], name='candidates__electio_f2c278_idx'), models.Index(fields=['constituency'], name='candidates__constit_59aac9_idx'), models.Index(fields=['gender'], name='candidates__gender_df32ef_idx'), models.Index(fields=['election_type'], name='candidates__electio_b57379_idx')],
                'constraints': [models.UniqueConstraint(fields=('election', 'source_id'), name='uq_candidate_election_source')],
            },
        ),
    ]
