# Generated by Django 5.1.15 on 2026-02-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
                (
                    "CREATE INDEX idx_candidate_name_ne_trgm ON candidates_candidate "
                    "USING gin (name_ne gin_trgm_ops);"
                ),
                (
                    "CREATE INDEX idx_candidate_name_trgm ON candidates_candidate "
                    "USING gin (name gin_trgm_ops);"
                ),
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_candidate_name_trgm;",
                "DROP INDEX IF EXISTS idx_candidate_name_ne_trgm;",
            ],
        ),
    ]
