# Generated by Django 5.1.15 on 2026-02-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_add_trigram_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='citizenship_district_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election_symbol_name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='father_name_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='candidate',
            name='inclusion_group_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_details_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='qualification_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='spouse_name_en',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
