# Generated by Django 5.1.15 on 2026-02-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'parties',
            },
        ),
    ]
